import HeaderApp from "@/components/header/HeaderApp";
import type { Metadata } from "next";
import "../styles/global.scss";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="main-layout">
          <HeaderApp />
          <div className="content-page">{children}</div>
        </main>
      </body>
    </html>
  );
}
